### ISSUE TITLE
Ensure any files are created with the correct permissions regardless of umask

### ISSUE THREAD

**Issue by liamellexus** [altairengineering/mistral_plugins#119]
**Goal:** Support multiple users

Files created by the plug-ins should be writable by other users, however the umask can prevent this happening. We should set the umask to 0 before creating any files that are common between runs e.g. the error log.

**Comment by liamellexus** [comment]
It was decided that we could fix this by changing the umask before launching the plugins in Mistral - in https://github.com/altairengineering/breeze-repo/issues/5084 - however I think that we should fix this when we get the chance.

**Comment by fcarsley** [comment]
This appears to have already been fixed as part of [f6f49d2](https://github.com/altairengineering/mistral_plugins/commit/f6f49d27693dccbfb4adac4fe7fcdff5d8b6a1c3), see [this file](https://github.com/altairengineering/mistral_plugins/blame/master/common/plugin_control.c#L229-L239)
