### ISSUE TITLE
All code files need license information in header

### ISSUE THREAD

**Issue by PaulEllexus** [altairengineering/mistral_plugins#14]
**Goal:** Legal protection

All source code in this repository may potentially be released to customers.  Our standard contracts for Mistral include terms and conditions that cover the licensing and use of source code, we just need to add a copyright statement and a "refer to your contract for full terms" statement to each code file in this repo.

Exact language of the comment to be confirmed.

**Comment by liamellexus** [comment]
It was decided to release this code with an MIT license that is in the repository. Does this still need to be done?
