### ISSUE TITLE
Compile/support plugins for ARM archs (armv7l and aarch64)

### ISSUE THREAD

**Issue by ponnuvel** [altairengineering/mistral_plugins#38]
Currently, it's not possible to compile plugins for ARM and PowerPC archs. To do this we need to:

1) Install curl and mysql cross-compilation libraries for ARM and PowerPC (build machines 10.33.0.106 and 10.33.0.108 respectively).
2) Modify the Makefiles and `package-plugins.sh` accordingly.

No code changes are required (already successfully compiled natively on the aarch64 Raspberry Pi - ellexus@10.33.100.190). 

Makefiles right now use `/usr/local/install/gcc-4.8.2/bin/gcc`:
```
common/Makefile:GCC ?= /usr/local/install/gcc-4.8.2/bin/gcc
output/mistral_elasticsearch/Makefile:GCC ?= /usr/local/install/gcc-4.8.2/bin/gcc
output/mistral_graphite/Makefile:GCC ?= /usr/local/install/gcc-4.8.2/bin/gcc
output/mistral_influxdb/Makefile:GCC ?= /usr/local/install/gcc-4.8.2/bin/gcc
output/mistral_mysql/Makefile:GCC ?= /usr/local/install/gcc-4.8.2/bin/gcc
output/mistral_rtm/Makefile:GCC ?= /usr/local/install/gcc-4.8.2/bin/gcc
```

which need to use the right compiler depending on the target release (`dryrun/common.mk` in breeze-repo would be helpful for this).

**Comment by liamellexus** [comment]
We now have builds for aarch64, but not PowerPC. Re-open this issue if needed.
